const LANGUAGES = {
    en: {
        translation: {
            page: 'Page',
            previous: 'Previous',
            next: 'Next',
            openPDF: 'Open',
            darkMode: 'Dark Mode',
            lightMode: 'Light Mode',
            zoomIn: 'Zoom In',
            zoomOut: 'Zoom Out',
            fitToPage: 'Fit to Page',
            fullScreen: 'Full Screen',
            exitFullScreen: 'Exit Full Screen',
            noDocument: 'No document loaded',
            loading: 'Loading...',
            dropZoneHint: 'Drop PDF here or click to open',
            shortcuts: 'Keyboard Shortcuts',
            shortcutsList: {
                pageNav: 'Change Page',
                zoom: 'Zoom In/Out',
                fit: 'Fit to Page',
                pageScroll: 'Page Navigation',
                zoomScroll: 'Zoom Control',
                print: 'Print Page',
                thumbnails: 'Toggle Thumbnails',
                theme: 'Toggle Theme',
                rotate: 'Rotate Page'
            },
            theme: 'Toggle Theme',
            print: 'Print Document [Experimental]',
            thumbnails: 'Thumbnails',
            thumbnailsTitle: 'Pages',
            showThumbnails: 'Show Thumbnails',
            hideThumbnails: 'Hide Thumbnails',
            scrollMode: 'Continuous Scroll [Experimental]',
            singlePage: 'Single Page'
        }
    },
    tr: {
        translation: {
            page: 'Sayfa',
            previous: 'Önceki',
            next: 'Sonraki',
            openPDF: 'Aç',
            darkMode: 'Karanlık Mod',
            lightMode: 'Aydınlık Mod',
            zoomIn: 'Yakınlaştır',
            zoomOut: 'Uzaklaştır',
            fitToPage: 'Sayfaya Sığdır',
            fullScreen: 'Tam Ekran',
            exitFullScreen: 'Tam Ekrandan Çık',
            noDocument: 'Döküman yüklenmedi',
            loading: 'Yükleniyor...',
            dropZoneHint: 'PDF\'i buraya sürükleyin veya tıklayarak açın',
            shortcuts: 'Klavye Kısayolları',
            shortcutsList: {
                pageNav: 'Sayfa Değiştir',
                zoom: 'Yakınlaştır/Uzaklaştır',
                fit: 'Sayfaya Sığdır',
                pageScroll: 'Sayfa Gezinme',
                zoomScroll: 'Yakınlaştırma Kontrolü',
                print: 'Sayfayı Yazdır',
                thumbnails: 'Küçük Resimleri Aç/Kapat',
                theme: 'Temayı Değiştir',
                rotate: 'Sayfayı Döndür'
            },
            theme: 'Temayı Değiştir',
            print: 'Belgeyi Yazdır [Deneysel]',
            thumbnails: 'Küçük Resimler',
            thumbnailsTitle: 'Sayfalar',
            showThumbnails: 'Küçük Resimleri Göster',
            hideThumbnails: 'Küçük Resimleri Gizle',
            scrollMode: 'Sürekli Kaydırma [Deneysel]',
            singlePage: 'Tek Sayfa'
        }
    },
    de: {
        translation: {
            page: 'Seite',
            previous: 'Zurück',
            next: 'Weiter',
            openPDF: 'Öffnen',
            darkMode: 'Dunkelmodus',
            lightMode: 'Hellmodus',
            zoomIn: 'Vergrößern',
            zoomOut: 'Verkleinern',
            fitToPage: 'An Seite anpassen',
            fullScreen: 'Vollbild',
            exitFullScreen: 'Vollbild beenden',
            noDocument: 'Kein Dokument geladen',
            loading: 'Wird geladen...',
            dropZoneHint: 'PDF hier ablegen oder klicken zum Öffnen',
            shortcuts: 'Tastaturkürzel',
            shortcutsList: {
                pageNav: 'Seite wechseln',
                zoom: 'Vergrößern/Verkleinern',
                fit: 'An Seite anpassen',
                pageScroll: 'Seitennavigation',
                zoomScroll: 'Zoomsteuerung',
                print: 'Seite drucken',
                thumbnails: 'Miniaturansichten ein/aus',
                theme: 'Design ändern',
                rotate: 'Seite drehen'
            },
            theme: 'Design ändern',
            print: 'Dokument drucken [Experimentell]',
            thumbnails: 'Miniaturansichten',
            thumbnailsTitle: 'Seiten',
            showThumbnails: 'Miniaturansichten anzeigen',
            hideThumbnails: 'Miniaturansichten ausblenden',
            scrollMode: 'Kontinuierlicher Bildlauf [Experimentell]',
            singlePage: 'Einzelseite'
        }
    },
    es: {
        translation: {
            page: 'Página',
            previous: 'Anterior',
            next: 'Siguiente',
            openPDF: 'Abrir',
            darkMode: 'Modo Oscuro',
            lightMode: 'Modo Claro',
            zoomIn: 'Acercar',
            zoomOut: 'Alejar',
            fitToPage: 'Ajustar a Página',
            fullScreen: 'Pantalla Completa',
            exitFullScreen: 'Salir de Pantalla Completa',
            noDocument: 'Sin documento',
            loading: 'Cargando...',
            dropZoneHint: 'Suelta el PDF aquí o haz clic para abrir',
            shortcuts: 'Atajos de Teclado',
            shortcutsList: {
                pageNav: 'Cambiar Página',
                zoom: 'Acercar/Alejar',
                fit: 'Ajustar a Página',
                pageScroll: 'Navegación de Página',
                zoomScroll: 'Control de Zoom',
                print: 'Imprimir Documento',
                thumbnails: 'Thumbnails',
                theme: 'Cambiar Tema',
                rotate: 'Rotar página'
            },
            theme: 'Cambiar Tema',
            print: 'Imprimir Documento [Experimental]',
            thumbnails: 'Miniaturas',
            thumbnailsTitle: 'Páginas',
            showThumbnails: 'Mostrar Miniaturas',
            hideThumbnails: 'Ocultar Miniaturas',
            scrollMode: 'Desplazamiento Continuo [Experimental]',
            singlePage: 'Página Única'
        }
    },
    fr: {
        translation: {
            page: 'Page',
            previous: 'Précédent',
            next: 'Suivant',
            openPDF: 'Ouvrir',
            darkMode: 'Mode Sombre',
            lightMode: 'Mode Clair',
            zoomIn: 'Zoom Avant',
            zoomOut: 'Zoom Arrière',
            fitToPage: 'Ajuster à la Page',
            fullScreen: 'Plein Écran',
            exitFullScreen: 'Quitter le Plein Écran',
            noDocument: 'Aucun document',
            loading: 'Chargement...',
            dropZoneHint: 'Déposez le PDF ici ou cliquez pour ouvrir',
            shortcuts: 'Raccourcis Clavier',
            shortcutsList: {
                pageNav: 'Changer de Page',
                zoom: 'Zoom Avant/Arrière',
                fit: 'Ajuster à la Page',
                pageScroll: 'Navigation des Pages',
                zoomScroll: 'Contrôle du Zoom',
                print: 'Imprimer Document',
                thumbnails: 'Thumbnails',
                theme: 'Changer de Thème',
                rotate: 'Rotation de la page'
            },
            theme: 'Changer de Thème',
            print: 'Imprimer Document [Expérimental]',
            thumbnails: 'Vignettes',
            thumbnailsTitle: 'Pages',
            showThumbnails: 'Afficher les Vignettes',
            hideThumbnails: 'Masquer les Vignettes',
            scrollMode: 'Défilement Continu [Expérimental]',
            singlePage: 'Page Unique'
        }
    },
    ru: {
        translation: {
            page: 'Страница',
            previous: 'Предыдущая',
            next: 'Следующая',
            openPDF: 'Открыть',
            darkMode: 'Темная тема',
            lightMode: 'Светлая тема',
            zoomIn: 'Увеличить',
            zoomOut: 'Уменьшить',
            fitToPage: 'По размеру',
            fullScreen: 'Полный экран',
            exitFullScreen: 'Выйти из полного экрана',
            noDocument: 'Документ не загружен',
            loading: 'Загрузка...',
            dropZoneHint: 'Перетащите PDF сюда или нажмите для открытия',
            shortcuts: 'Горячие клавиши',
            shortcutsList: {
                pageNav: 'Сменить страницу',
                zoom: 'Увеличить/Уменьшить',
                fit: 'По размеру',
                pageScroll: 'Навигация по страницам',
                zoomScroll: 'Управление масштабом',
                print: 'Печать документа',
                thumbnails: 'Thumbnails',
                theme: 'Сменить тему',
                rotate: 'Повернуть страницу'
            },
            theme: 'Сменить тему',
            print: 'Печать документа [Экспериментальный]',
            thumbnails: 'Миниатюры',
            thumbnailsTitle: 'Страницы',
            showThumbnails: 'Показать Миниатюры',
            hideThumbnails: 'Скрыть Миниатюры',
            scrollMode: 'Непрерывная Прокрутка',
            singlePage: 'Одна Страница'
        }
    },
    ar: {
        translation: {
            page: 'صفحة',
            previous: 'السابق',
            next: 'التالي',
            openPDF: 'فتح',
            darkMode: 'الوضع الداكن',
            lightMode: 'الوضع الفاتح',
            zoomIn: 'تكبير',
            zoomOut: 'تصغير',
            fitToPage: 'ملاءمة للصفحة',
            fullScreen: 'ملء الشاشة',
            exitFullScreen: 'الخروج من ملء الشاشة',
            noDocument: 'لم يتم تحميل أي مستند',
            loading: 'جاري التحميل...',
            dropZoneHint: 'اسحب ملف PDF هنا أو انقر للفتح',
            shortcuts: 'اختصارات لوحة المفاتيح',
            shortcutsList: {
                pageNav: 'تغيير الصفحة',
                zoom: 'تكبير/تصغير',
                fit: 'ملاءمة للصفحة',
                pageScroll: 'التنقل بين الصفحات',
                zoomScroll: 'التحكم في التكبير',
                print: 'طباعة المستند',
                thumbnails: 'Thumbnails',
                theme: 'تبديل السمة',
                rotate: 'تدوير الصفحة'
            },
            theme: 'تبديل السمة',
            print: 'طباعة المستند [تجريبي]',
            thumbnails: 'مصغرات',
            thumbnailsTitle: 'الصفحات',
            showThumbnails: 'إظهار المصغرات',
            hideThumbnails: 'إخفاء المصغرات',
            scrollMode: 'تمرير مستمر',
            singlePage: 'صفحة واحدة'
        }
    },
    ko: {
        translation: {
            page: '페이지',
            previous: '이전',
            next: '다음',
            openPDF: '열기',
            darkMode: '다크 모드',
            lightMode: '라이트 모드',
            zoomIn: '확대',
            zoomOut: '축소',
            fitToPage: '페이지에 맞추기',
            fullScreen: '전체 화면',
            exitFullScreen: '전체 화면 종료',
            noDocument: '문서가 로드되지 않음',
            loading: '로딩 중...',
            dropZoneHint: 'PDF를 여기에 드롭하거나 클릭하여 열기',
            shortcuts: '키보드 단축키',
            shortcutsList: {
                pageNav: '페이지 변경',
                zoom: '확대/축소',
                fit: '페이지에 맞추기',
                pageScroll: '페이지 탐색',
                zoomScroll: '줌 제어',
                print: '문서 인쇄',
                thumbnails: 'Thumbnails',
                theme: '테마 전환',
                rotate: '페이지 회전'
            },
            theme: '테마 전환',
            print: '문서 인쇄 [실험적]',
            thumbnails: '미리보기',
            thumbnailsTitle: '페이지',
            showThumbnails: '미리보기 표시',
            hideThumbnails: '미리보기 숨기기',
            scrollMode: '연속 스크롤',
            singlePage: '단일 페이지'
        }
    },
    zh: {
        translation: {
            page: '页面',
            previous: '上一页',
            next: '下一页',
            openPDF: '打开',
            darkMode: '深色模式',
            lightMode: '浅色模式',
            zoomIn: '放大',
            zoomOut: '缩小',
            fitToPage: '适应页面',
            fullScreen: '全屏',
            exitFullScreen: '退出全屏',
            noDocument: '未加载文档',
            loading: '加载中...',
            dropZoneHint: '将PDF拖放到此处或点击打开',
            shortcuts: '键盘快捷键',
            shortcutsList: {
                pageNav: '切换页面',
                zoom: '放大/缩小',
                fit: '适应页面',
                pageScroll: '页面导航',
                zoomScroll: '缩放控制',
                print: '打印文档',
                thumbnails: 'Thumbnails',
                theme: '切换主题',
                rotate: '旋转页面'
            },
            theme: '切换主题',
            print: '打印文档 [实验性]',
            thumbnails: '缩略图',
            thumbnailsTitle: '页面',
            showThumbnails: '显示缩略图',
            hideThumbnails: '隐藏缩略图',
            scrollMode: '连续滚动',
            singlePage: '单页'
        }
    },
    it: {
        translation: {
            page: 'Pagina',
            previous: 'Precedente',
            next: 'Successiva',
            openPDF: 'Apri',
            darkMode: 'Modalità Scura',
            lightMode: 'Modalità Chiara',
            zoomIn: 'Ingrandisci',
            zoomOut: 'Riduci',
            fitToPage: 'Adatta alla Pagina',
            fullScreen: 'Schermo Intero',
            exitFullScreen: 'Esci da Schermo Intero',
            noDocument: 'Nessun documento',
            loading: 'Caricamento...',
            dropZoneHint: 'Trascina qui il PDF o clicca per aprire',
            shortcuts: 'Scorciatoie da Tastiera',
            shortcutsList: {
                pageNav: 'Cambia Pagina',
                zoom: 'Ingrandisci/Riduci',
                fit: 'Adatta alla Pagina',
                pageScroll: 'Navigazione Pagina',
                zoomScroll: 'Controllo Zoom',
                print: 'Stampa Documento',
                thumbnails: 'Thumbnails',
                theme: 'Cambia Tema',
                rotate: 'Ruota pagina'
            },
            theme: 'Cambia Tema',
            print: 'Stampa Documento [Sperimentale]',
            thumbnails: 'Anteprime',
            thumbnailsTitle: 'Pagine',
            showThumbnails: 'Mostra Anteprime',
            hideThumbnails: 'Nascondi Anteprime',
            scrollMode: 'Scorrimento Continuo',
            singlePage: 'Pagina Singola'
        }
    },
    ja: {
        translation: {
            page: 'ページ',
            previous: '前へ',
            next: '次へ',
            openPDF: '開く',
            darkMode: 'ダークモード',
            lightMode: 'ライトモード',
            zoomIn: '拡大',
            zoomOut: '縮小',
            fitToPage: 'ページに合わせる',
            fullScreen: '全画面',
            exitFullScreen: '全画面を終了',
            noDocument: '文書が読み込まれていません',
            loading: '読み込み中...',
            dropZoneHint: 'PDFをここにドロップまたはクリックして開く',
            shortcuts: 'キーボードショートカット',
            shortcutsList: {
                pageNav: 'ページ切り替え',
                zoom: '拡大/縮小',
                fit: 'ページに合わせる',
                pageScroll: 'ページナビゲーション',
                zoomScroll: 'ズーム制御',
                print: 'ドキュメントを印刷',
                thumbnails: 'Thumbnails',
                theme: 'テーマ切り替え',
                rotate: 'ページを回転'
            },
            theme: 'テーマ切り替え',
            print: 'ドキュメントを印刷 [実験的]',
            thumbnails: 'サムネイル',
            thumbnailsTitle: 'ページ',
            showThumbnails: 'サムネイルを表示',
            hideThumbnails: 'サムネイルを非表示',
            scrollMode: '連続スクロール',
            singlePage: '単一ページ'
        }
    }
};

/* AI handled most of the translations. There may be mistakes. */